# Run `travis lint` when changing this file to avoid breaking the build.
dist: focal
language: java
# Intentionally don't use "jdk" key as it is coupled to jdk.java.net availability.
addons:
  apt:
    update: true

cache:
  directories:
    - $HOME/.m2

before_install:
  # Use JDK 11, so we can release Java 6 bytecode
  - export JAVA_VERSION=11
  - sudo apt-get -y install openjdk-$JAVA_VERSION-jdk
  - export JAVA_HOME=/usr/lib/jvm/java-$JAVA_VERSION-openjdk-amd64/
  - ./mvnw -version
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  # Only attempt to decrypt secrets when it's not a PR and has access to secure env var
  # Encrypted signing keys are used for the release profile
  #   Ex. travis encrypt-file travis/signing_key.gpg
  # When updating this, you also must update the encrypted GPG_PASSPHRASE at the bottom of this file
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      export GPG_TTY=$(tty) &&
      openssl aes-256-cbc -K $encrypted_911894d24f52_key -iv $encrypted_911894d24f52_iv -in travis/signing_key.gpg.enc -out signing_key.gpg -d &&
      gpg --batch --passphrase $GPG_PASSPHRASE --import signing_key.gpg && rm signing_key.gpg;
    fi;

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/9f1ee2f315d32956f8d6
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "iQOxpVn9SWf945dIQcFAkShnmvvzJYHYeYFNj3XhaveG3eGhkpSiOzPjkom8cTRceXdqhBztDzuAHm9MsB5GAhgik/KV1Lg2HH055+JBpvjkPvieV0H2DDwuqEbL5Qs3MiEkJ/Ar2d3nCBR1DWlWqTa03fkMuNUIRo7+0Dauq5jiAVZF84yccboyRrL9wd7BcdnxF+JRQENtUrT4QrHkW7rwEJzc1djj8wGOwXz7fX/9SFQjnblIzRIGOyLgdb5nNEnGuZTOmaJ4ZagoTT8/eZGodp3qSKwywf7jvbk+K0VofXKA8M9P55cXtSjNRWiz9dWog0lkIz/fGUhp9/c0XbgcdvwPnbFHsPaF+8XsrjvJmyBUxP+ovHJ/ePgZkxZ1KqbLe8xXI7aPJZnNTIdsESjh5qrNVhfHttcxzmCWBG3R1ER0Rmab00/py4OUHMaBrvhfWUVn7Rj7Z3igRNZRYM8kWoaa5qxavEpFvzXuY3+6alkf/lpY8qzH8GIFby/qKJlylfGWfGO1Bt2tRSRuqbppIQ4HmGOM1SRpsGQpAFUaFGQb4VGbFXYfXi21qFpPd/q8rr3pMr/OljjR7L1EEzoAtDWlMouhtxpUfznZX1FAYZpGtla9zY1ViiUX3sl9qky2a7hHAwrSE/oxxcwc9/RfByhObU/tpFpJ/4gx47g="
    # Ex. travis encrypt GPG_PASSPHRASE=passphrase_for_travis/signing_key.gpg
    - secure: "c3ybLYinzNEWthHZk4fqfcX7Ftah0VPtQKUlnco6y66cCbMhuM6XaE4Fzu7n8RchuLRMpifnseYj+/oH/8k84QgVrnRNKmT/DEtHoWOP61GV6DWs8EcDA3gTQ45XnMmN9AgXHZD1t+QEtK013nGhNicAm7jzhE0+Je3Ix5QdIMsDiB1rzzJfN8BsSbDlRxuEF7Szf3Lz/FR6WOuA0Yo6AFPbqTKcKxHC19+ahzfSh38Z+LUsEFg489TeAzu4ye8xjYFdcdkHaT4hxeBFX2SixShYzJFEolfxvEAsHonyaLElG2XLr5ZK6glQch+0xGyeHxJyuOaYWfGV+nGw2lAPJWPfdfd9cXhE6eFj1R96/eAJqzC3dveyOQ0lM7nVxJXsJnIdww/KbctE1ja7nbzOePCGh3C3cQl97yNSNHsrapdWmv/39EMCWG5/1CjNMbLXKZ8kPhkH+7BR3idkf96bu/aCJqJlWjO30NH/VtkDJxJlPQQ91LBjEMRnYZYiRxmolVI+y1rriuPbPQkm+R2XkMBCc2m8klQE7hVVQ4PYBf+pR77hTsQ8LTySwCADmZPyxgAtmw6gyl61sTtPcjzC9KWx1kNHtwAxeOnP0vhzQApNUFBDGdKehfH+NcYw7IDiH1cktmCRLGP2bB8EqxLZBaDz/WttEcXUpccz3K+hOSI="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "cz5RYAxEvZyV8ZhIr2bsocxGoE10q5mmSIKST31z7J2lFBRPbybnB+ZDTwAnfIdAy7/ROihbqD+0FM7u6S0OzW57HcXzDclKSDd2tPwWcjW+HSKvzn/i8wXEOGhby62tmIY1OwkCmgSW4FMPFhNWR44ijv0DPE4YTIAqSvfyDLxChozPJj2bG57mFFPGu7L0Ap6WbAxPziomvbUPpQKaGBWl0R8ADQaSLz/zJ7t9oo8YYvlKcezJJXnxmGc33JXTzUewXXHaKdHty0evw1xi0+rDRTRA++hOaxJnOhbfcAIEAI/kZXXNnH+N1xDIRcJL8x1m6i4uanlFZgpasYavHsczAAfGC2NscpfEp0akSSQMTPFVx7ECqwLejW3NeZnWiU1dSGunaaIm6Hf9pGziSXbNfqQDO6e8DI41f+p3jm4vURykf16IN8zu1PMteBO43q8bmBSbdPno/zBloJxny39SdV24a8obe85dxOsJClsDaXVr1jPSUMSCz5/pXv+GugmPORxBvsqYvjCeWfU3vp1AoEa4Am0eLGbpCsCRd+gg261suUzDM0Xj0Wn4t/CQmtNd+YLiRrUwjL8E8YBclMmcqWZ1v5gqItLxwHKfXmrXKZ9xeST7Z1Y1b+VZ/pYARYBrD+hsY/ewUCceGZ/0HLUj9QNcPVJzyI9gmtHHbyY="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "m0qqc0qXpc4G8ax6Bah1f+KqFwNTTztPMwaCuVSucm0PH8td2r/pURrzo++wIjMBZFGVEtvxFqLvKTBwh4oLGTjHWIXt+MWnfWesld7lPFwlB+ryajHM48sMLVo3gHSAchJXk8u+UiiWcrRfJCqDqdI0vf4PXPU+taSFEbPKmoDtbKuHuRE/5DjMRDBk+BkMcJCtwAE/F+ZH1INB/A9PPQDiVHe7rWr3csFItVouosotCvvRi7oCEqNhbOVYeCpMfkU7Xuvu9R1y7DkMBvynLTsMaPIKuJMHbD53vpXbOW1OEWxjH9Ai6d7ymETXdJKZ2SuM17xjokyUsTWtMutqW1W37zQ5pFJ1qA4vesrLjgvBI0prRheYel/f3dNkJII5sNnJS5fqyTLLqrWRBBiKwzJFtXMyXOayuH1k+C4hWZIjakCNyl/7qvJLm8PjBTT6ZiYQNlzOJf+sZXWv2YfB7tMz6W6SPt704IPmz5URQ6teFCtAEz3Iumf1paaii9jKrhr+UriEp3Lazv0qT2ffNHT1K8V9fado9R9u9culFj9fSatYvF3L+u9yrhf6vOOYRhQCCd4YVPlFwH4BChGGvwFqYLkfp82pEWMqnQ7Bf/jZM3MAuof8WVBXXds2kIvtH/fWUYf1Vydx/2spr1GZoL6hfzlIw+pyB6mWpWJH3Pw="
